# TOML interpretation of the https://github.com/nordtheme/alacritty
# See also: https://github.com/nordtheme/alacritty/issues/40
# (if the above is resolved, you may not need this Gist)

# Nightfox Alacritty Colors
## name: nightfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/alacritty.toml

[colors.primary]
background = "#192330"
foreground = "#cdcecf"
dim_foreground = "#aeafb0"
bright_foreground = "#d6d6d7"

[colors.cursor]
text = "#cdcecf"
cursor = "#aeafb0"

[colors.vi_mode_cursor]
text = "#cdcecf"
cursor = "#63cdcf"

[colors.search.matches]
foreground = "#cdcecf"
background = "#3c5372"

[colors.search.focused_match]
foreground = "#cdcecf"
background = "#81b29a"

[colors.footer_bar]
foreground = "#cdcecf"
background = "#29394f"

[colors.hints.start]
foreground = "#cdcecf"
background = "#f4a261"

[colors.hints.end]
foreground = "#cdcecf"
background = "#29394f"

[colors.selection]
text = "#cdcecf"
background = "#2b3b51"

[colors.normal]
black = "#393b44"
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"
blue = "#719cd6"
magenta = "#9d79d6"
cyan = "#63cdcf"
white = "#dfdfe0"

[colors.bright]
black = "#575860"
red = "#d16983"
green = "#8ebaa4"
yellow = "#e0c989"
blue = "#86abdc"
magenta = "#baa1e2"
cyan = "#7ad5d6"
white = "#e4e4e5"

[colors.dim]
black = "#30323a"
red = "#ab435d"
green = "#6e9783"
yellow = "#baa363"
blue = "#6085b6"
magenta = "#8567b6"
cyan = "#54aeb0"
white = "#bebebe"

[[colors.indexed_colors]]
index = 16
color = "#f4a261"

[[colors.indexed_colors]]
index = 17
color = "#d67ad2"


# [colors.primary]
# background = "#2e3440"
# foreground = "#d8dee9"
# dim_foreground = "#a5abb6"
#
# [colors.cursor]
# text = "#2e3440"
# cursor = "#d8dee9"
#
# [colors.vi_mode_cursor]
# text = "#2e3440"
# cursor = "#d8dee9"
#
# [colors.selection]
# text = "CellForeground"
# background = "#4c566a"
#
# [colors.search.matches]
# foreground = "CellBackground"
# background = "#88c0d0"
#
# [colors.footer_bar]
# background = "#434c5e"
# foreground = "#d8dee9"
#
# [colors.normal]
# black = "#3b4252"
# red = "#bf616a"
# green = "#a3be8c"
# yellow = "#ebcb8b"
# blue = "#81a1c1"
# magenta = "#b48ead"
# cyan = "#88c0d0"
# white = "#e5e9f0"
#
# [colors.bright]
# black = "#4c566a"
# red = "#bf616a"
# green = "#a3be8c"
# yellow = "#ebcb8b"
# blue = "#81a1c1"
# magenta = "#b48ead"
# cyan = "#8fbcbb"
# white = "#eceff4"
#
# [colors.dim]
# black = "#373e4d"
# red = "#94545d"
# green = "#809575"
# yellow = "#b29e75"
# blue = "#68809a"
# magenta = "#8c738c"
# cyan = "#6d96a5"
# white = "#aeb3bb"


# [colors.bright]
# black = "#636363"
# blue = "#7eaac7"
# cyan = "#86d3ce"
# green = "#909d63"
# magenta = "#aa6292"
# red = "#bc5653"
# white = "#f7f7f7"
# yellow = "#ebc17a"
#
# [colors.cursor]
# cursor = "#d9d9d9"
# text = "#2c2c2c"
#
# [colors.dim]
# black = "#232323"
# blue = "#556b79"
# cyan = "#5c8482"
# green = "#5e6547"
# magenta = "#6e4962"
# red = "#74423f"
# white = "#828282"
# yellow = "#8b7653"
#
# [colors.normal]
# black = "#1c1c1c"
# blue = "#7eaac7"
# cyan = "#86d3ce"
# green = "#909d63"
# magenta = "#aa6292"
# red = "#bc5653"
# white = "#cacaca"
# yellow = "#ebc17a"
#
# [colors.primary]
# background = "#2c2c2c"
# foreground = "#d6d6d6"

[env]
TERM = "alacritty"

[font]
size = 18.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
key = "="
mods = "Command"
action = "IncreaseFontSize"

[scrolling]
history = 10000

[window]
dynamic_title = true
option_as_alt = "None"
decorations = "Buttonless"

[window.padding]
x = 5
y = 3
